### ISSUE TITLE
adapter wiring

### ISSUE THREAD

**Issue by genehunter29009** [juanmb/NexStarAdapter#3]
I am new to building projects like this but , I have successfully compiled the code for  and esp32 and I have a question about the wiring diagram for the connector. I cant tell if this is looking from the back or looking from the front. It makes a difference you know so I am not sure what the standard is for this type of drawing.

**Comment by juanmb** [comment]
Yes, you are right. I have to fix that diagram.
In [this page](https://sites.google.com/site/wayneholder/nexstar-direct-telescope-mount-control) you can check the correct pinout of the AUX connector.
